platform :ios, '10.0'
target 'Halaat Updates' do

  use_frameworks!
  
      pod 'Alamofire', '~> 4.2.0'
      pod 'SDWebImage', '~> 4.0'
      pod 'ObjectMapper', '~> 2.2'
      pod 'Firebase/Core'
      pod 'Firebase/Auth'
      pod 'Firebase/Database'
      pod 'Firebase/Storage'
      pod 'RxSwift'
      pod 'RxCocoa'
end
